In [8]:
import numpy as np

### Question 1

Given the following numpy array:
arr = np.array([1, 2, 3, 4, 5])
Write a Python code to multiply each element in the array by 2.

In [9]:
arr = np.array([1, 2, 3, 4, 5])

In [10]:
arr * 2

array([ 2,  4,  6,  8, 10])

### Question 2

Given the following 2D numpy array:

```python
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
```

Write a Python code to select the second row of the array.

Answer:



In [12]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
arr[1]

array([4, 5, 6])

Question 3

Create a 2D numpy array of shape (5, 5) filled with the number 1.

Answer:

In [15]:
arr = np.ones((5, 5))
arr

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

Question 4

Given the following 2D numpy array:

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

Write a Python code to calculate the sum of all the elements in each row.

Answer:

In [16]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
row_sums=arr.sum(axis=1)
row_sums

array([12, 15, 18])

In [23]:
col_sums=arr.sum(axis=0)
col_sums

array([12, 15, 18])

Question 5

Given the following 2D numpy array:

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

Write a Python code to calculate the average of all the elements.

Answer:

In [24]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [25]:
avg=arr.mean()
avg

5.0